[tool.poetry]
name = "various"
version = "0.1.0"
description = ""
authors = ["minhcccp <33189614+minhcccp@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = { version = "^21.6b0", allow-prereleases = true }
jupyter = { version = "^1.0.0", allow-prereleases = true }
pytest = { version = "^6.2.4", allow-prereleases = true }
rope = {version = "^0.19.0", allow-prereleases = true}
wily = { version = "^1.20.0", allow-prereleases = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
