[tool.poetry]
name = "various"
version = "0.1.0"
description = ""
license = "GPL-3.0-or-later"
authors = ["minhcccp <33189614+minhcccp@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

beartype = { allow-prereleases = true, version = "^0.8.1" }
codetiming = { allow-prereleases = true, version = "^1.3.0" }
more-itertools = { allow-prereleases = true, version = "^8.8.0" }
prettytable = { allow-prereleases = true, version = "^2.1.0" }
sympy = { allow-prereleases = true, version = "^1.8" }

gmpy2 = { url = "https://github.com/aleaxit/gmpy/releases/download/gmpy2-2.1.0rc1/gmpy2-2.1.0rc1-cp39-cp39-win_amd64.whl" }

[tool.poetry.dev-dependencies]
black = { allow-prereleases = true, extras = ["jupyter"], version = "^21.8b0" }
identify = { allow-prereleases = true, version = "^2.2.13" }
isort = { allow-prereleases = true, version = "^5.9.3" }
jupyter = { allow-prereleases = true, version = "^1.0.0" }
nbqa = { allow-prereleases = true, version = "^1.1.0" }
pre-commit = { allow-prereleases = true, version = "^2.15.0" }
pytest = { allow-prereleases = true, version = "^6.2.4" }
wily = { allow-prereleases = true, version = "^1.20.0" }

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
